### ISSUE TITLE
How to use the standalone  liblowfat.so

### ISSUE THREAD

**Issue by liang1232018** [GJDuck/LowFat#14]
Hi ,GJDuck
I have successful build the Lowfat by using the ` ./build.sh`
And I also successful by `clang  -fsanitize=lowfat`

But, when I want to use the stanalone Mode, It seems the compile-rt can not be ld.
I first use the
 `opt -load ~/LowFat/LowFat.so < xxxx.bc > xxx_lowfat.bc  -lowfat -O2`
and I got a new bc with lowfat pass 
But when I ld the liblowfat.so? I have try to 
`ld  xxx_lowfat.o -o xxxx_lowfat.out   liblowfat.preload.so liblowfat.so -ldl`
However, the  **xxxx_lowfat.out**  can not run correctly. 
I want to know how to use the standalone mode?
Thanks, for help.

Best,Daliang

**Comment by GJDuck** [comment]
You'd need to link against the static `libclang_rt.lowfat-x86_64.a` library that should be somewhere in the `build` directory.  But even this will probably not work correctly.  The only "official" way of using LowFat is via `clang -fsanitize=lowfat`, since this also enables the necessary compiler flags, linker flags, optimization passes, and ld scripts, etc.

The `LowFat.so` and `liblowfat*.so` files are mainly included for building LowFat extensions or for other projects.  For example, I think the `preload` is a stripped-down version of the runtime that only includes the heap allocator.  This can be used to replace standard `malloc` using `LD_PRELOAD` for performance testing or other reasons.

**Comment by liang1232018** [comment]
OK , I see.  Thanks for great help !

**Comment by GJDuck** [comment]
No problem.
