### ISSUE TITLE
Missed error

### ISSUE THREAD

**Issue by janhoogerbrugge** [GJDuck/LowFat#2]
Hi,

The following code shows that writing out of bounds in one local array changes another array without error reporting.

I have an old PC so it working in legacy mode.

Regards,
Jan.

~/LowFat/test % cat test.c
#include <stdio.h>

extern void foo(int *, int);

int main()
{
  int a[100] = {0};
  int b[100] = {0};

  printf("distance = %ld\n", a - b);

  printf("a[0] = %d\n", a[0]);
  printf("b[0] = %d\n", b[0]);

  foo(b, 128);

  printf("a[0] = %d\n", a[0]);
  printf("b[0] = %d\n", b[0]);

  return 0;
}
~/LowFat/test % cat test2.c
void foo(int *p, int i)
{
  p[i]++;
}
~/LowFat/test % clang -O2 -fsanitize=lowfat test.c test2.c && a.out 
distance = 128
a[0] = 0
b[0] = 0
a[0] = 1
b[0] = 0

**Comment by GJDuck** [comment]
Thanks for the report.  The problem was that the bounds check was using the wrong test, namely (`<`) instead of (`<=`), resulting in an off-by-one-error.  The `check-whole-access` mode was not affected.

The issue should be now be fixed.  I've added a `test/issue_2.c` test program for future reference.
