### ISSUE TITLE
malloc (lowfat_malloc_index) does not return pointer to the right region

### ISSUE THREAD

**Issue by janhoogerbrugge** [GJDuck/LowFat#6]
Hi,

Running this test program (in legacy mode):

char g1[15];
char g2[31];

void test(char *a, int i)
{
  a[i]++;
}

int main()
{
  char l1[15];
  char l2[31];

  char *h1 = malloc(15);
  char *h2 = malloc(31);

  printf("%ld\n", (long) l1 >> 35);
  printf("%ld\n", (long) l2 >> 35);
  printf("%ld\n", (long) g1 >> 35);
  printf("%ld\n", (long) g2 >> 35);
  printf("%ld\n", (long) h1 >> 35);
  printf("%ld\n", (long) h2 >> 35);

  //test(l1, 16);       // detected
  //test(g1, 16);       // detected
  //test(h1, 16);       // not detected
  
  return 0;
}

gives:

1
2
1
2
64
64

The lowfat system is configured with 'size2.cfg 32'. As you can see the pointers to globals
and locals are in the correct region. This is not the case for heap pointers. OOB accesses
to the globals and locals are correctly detected but the access to the heap is not detected.

If I replace the mallocs by:

  char *h1 = lowfat_malloc_index(1, 15);
  char *h2 = lowfat_malloc_index(2, 31);

then the result is the same.

**Comment by GJDuck** [comment]
Thanks for the report.  This was a bug caused by a broken macro renaming that was introduced just before release.  Another bug was that the test suite failed to detect the problem.  Both bugs should now be fixed.

(Edit) Summary of the problem:

This bug only affected the power-of-two mode, and was caused by a configuration macro renaming that was not reflected in the `lowfat.h` header file.  This meant that the header's definition of `lowfat_base` was using the non-power-of-two definition in power-of-two mode, and this caused `lowfat_malloc` to get confused. The lowfat heap allocator would then revert to libc's `malloc` instead, and thus would return non-fat pointers meaning that the corresponding objects are not bounds protected.  This only affected the runtime library --- the instrumented version of `lowfat_base` still used the correct definition.
