### ISSUE TITLE
Running SPEC CPU2006

### ISSUE THREAD

**Issue by dokyungs** [GJDuck/LowFat#7]
Hi,

I am trying to run SPEC CPU2006 INT benchmark suite. But apparently a couple of the benchmarks are failing with OOB escape. Is there any patch available for SPEC? Or do you have any recommendation on compilation flags or lowfat config?

Thanks!

**Comment by GJDuck** [comment]
Some functions from `perlbench` and `gcc` use OOB-escapes IIRC.  You can "blacklist" the functions using the `-mllvm -lowfat-no-check-blacklist=blacklist.txt` option, where `blacklist.txt` is in the LLVM *special case list* format (see [here](https://clang.llvm.org/docs/SanitizerSpecialCaseList.html)).  I recall about ~20 functions from SPEC are affected.

There isn't an "official" list since it depends on compiler version/flags.  E.g., if a function call that uses OOB-escapes gets inlined then the problem goes away.
